export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS"
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

export const PRODUCT_GET_BY_ID_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_GET_BY_ID_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_GET_BY_ID_FAIL = "PRODUCT_FAIL"

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
